baseURL: https://blog.leonb.cc/
languageCode: en-us
title: Leon's Blog
theme: "PaperMod"
enableRobotsTXT: true

params:
  homeInfoParams:
    Title: Welcome to my random thoughts and ramblings on the world and mostly tech.
    Content: I currently work at AWS as an SDE. All the thoughts and opinions presented here are my own.
